//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_b0_H
#define METASPRITE_b0_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define b0_TILE_ORIGIN 0
#define b0_TILE_W 8
#define b0_TILE_H 16
#define b0_WIDTH 16
#define b0_HEIGHT 16
#define b0_TILE_COUNT 4
#define b0_PALETTE_COUNT 1
#define b0_COLORS_PER_PALETTE 4
#define b0_TOTAL_COLORS 4
#define b0_PIVOT_X 8
#define b0_PIVOT_Y 8
#define b0_PIVOT_W 16
#define b0_PIVOT_H 16
extern const metasprite_t* const b0_metasprites[1];

BANKREF_EXTERN(b0)

extern const palette_color_t b0_palettes[4];
extern const uint8_t b0_tiles[64];

#endif
