//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ba32_H
#define METASPRITE_ba32_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ba32_TILE_ORIGIN 0
#define ba32_TILE_W 8
#define ba32_TILE_H 16
#define ba32_WIDTH 16
#define ba32_HEIGHT 16
#define ba32_TILE_COUNT 4
#define ba32_PALETTE_COUNT 1
#define ba32_COLORS_PER_PALETTE 4
#define ba32_TOTAL_COLORS 4
#define ba32_PIVOT_X 8
#define ba32_PIVOT_Y 8
#define ba32_PIVOT_W 16
#define ba32_PIVOT_H 16
extern const metasprite_t* const ba32_metasprites[1];

BANKREF_EXTERN(ba32)

extern const palette_color_t ba32_palettes[4];
extern const uint8_t ba32_tiles[64];

#endif
