//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ba64_H
#define METASPRITE_ba64_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ba64_TILE_ORIGIN 0
#define ba64_TILE_W 8
#define ba64_TILE_H 16
#define ba64_WIDTH 16
#define ba64_HEIGHT 16
#define ba64_TILE_COUNT 4
#define ba64_PALETTE_COUNT 1
#define ba64_COLORS_PER_PALETTE 4
#define ba64_TOTAL_COLORS 4
#define ba64_PIVOT_X 8
#define ba64_PIVOT_Y 8
#define ba64_PIVOT_W 16
#define ba64_PIVOT_H 16
extern const metasprite_t* const ba64_metasprites[1];

BANKREF_EXTERN(ba64)

extern const palette_color_t ba64_palettes[4];
extern const uint8_t ba64_tiles[64];

#endif
