//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bu32_H
#define METASPRITE_bu32_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bu32_TILE_ORIGIN 0
#define bu32_TILE_W 8
#define bu32_TILE_H 16
#define bu32_WIDTH 16
#define bu32_HEIGHT 16
#define bu32_TILE_COUNT 4
#define bu32_PALETTE_COUNT 1
#define bu32_COLORS_PER_PALETTE 4
#define bu32_TOTAL_COLORS 4
#define bu32_PIVOT_X 8
#define bu32_PIVOT_Y 8
#define bu32_PIVOT_W 16
#define bu32_PIVOT_H 16
extern const metasprite_t* const bu32_metasprites[1];

BANKREF_EXTERN(bu32)

extern const palette_color_t bu32_palettes[4];
extern const uint8_t bu32_tiles[64];

#endif
