//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bg_H
#define METASPRITE_bg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bg_TILE_ORIGIN 0
#define bg_TILE_W 8
#define bg_TILE_H 8
#define bg_WIDTH 160
#define bg_HEIGHT 144
#define bg_TILE_COUNT 77
#define bg_PALETTE_COUNT 1
#define bg_COLORS_PER_PALETTE 4
#define bg_TOTAL_COLORS 4
#define bg_MAP_ATTRIBUTES 0
extern const unsigned char bg_map[360];
#define bg_map_attributes bg_map

BANKREF_EXTERN(bg)

extern const palette_color_t bg_palettes[4];
extern const uint8_t bg_tiles[1232];

#endif
