//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bu64_H
#define METASPRITE_bu64_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bu64_TILE_ORIGIN 0
#define bu64_TILE_W 8
#define bu64_TILE_H 16
#define bu64_WIDTH 16
#define bu64_HEIGHT 16
#define bu64_TILE_COUNT 4
#define bu64_PALETTE_COUNT 1
#define bu64_COLORS_PER_PALETTE 4
#define bu64_TOTAL_COLORS 4
#define bu64_PIVOT_X 8
#define bu64_PIVOT_Y 8
#define bu64_PIVOT_W 16
#define bu64_PIVOT_H 16
extern const metasprite_t* const bu64_metasprites[1];

BANKREF_EXTERN(bu64)

extern const palette_color_t bu64_palettes[4];
extern const uint8_t bu64_tiles[64];

#endif
