//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_b02_H
#define METASPRITE_b02_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define b02_TILE_ORIGIN 0
#define b02_TILE_W 8
#define b02_TILE_H 16
#define b02_WIDTH 16
#define b02_HEIGHT 16
#define b02_TILE_COUNT 4
#define b02_PALETTE_COUNT 1
#define b02_COLORS_PER_PALETTE 4
#define b02_TOTAL_COLORS 4
#define b02_PIVOT_X 8
#define b02_PIVOT_Y 8
#define b02_PIVOT_W 16
#define b02_PIVOT_H 16
extern const metasprite_t* const b02_metasprites[1];

BANKREF_EXTERN(b02)

extern const palette_color_t b02_palettes[4];
extern const uint8_t b02_tiles[64];

#endif
