//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ba322_H
#define METASPRITE_ba322_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ba322_TILE_ORIGIN 0
#define ba322_TILE_W 8
#define ba322_TILE_H 16
#define ba322_WIDTH 16
#define ba322_HEIGHT 16
#define ba322_TILE_COUNT 4
#define ba322_PALETTE_COUNT 1
#define ba322_COLORS_PER_PALETTE 4
#define ba322_TOTAL_COLORS 4
#define ba322_PIVOT_X 8
#define ba322_PIVOT_Y 8
#define ba322_PIVOT_W 16
#define ba322_PIVOT_H 16
extern const metasprite_t* const ba322_metasprites[1];

BANKREF_EXTERN(ba322)

extern const palette_color_t ba322_palettes[4];
extern const uint8_t ba322_tiles[64];

#endif
