//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ba642_H
#define METASPRITE_ba642_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ba642_TILE_ORIGIN 0
#define ba642_TILE_W 8
#define ba642_TILE_H 16
#define ba642_WIDTH 16
#define ba642_HEIGHT 16
#define ba642_TILE_COUNT 4
#define ba642_PALETTE_COUNT 1
#define ba642_COLORS_PER_PALETTE 4
#define ba642_TOTAL_COLORS 4
#define ba642_PIVOT_X 8
#define ba642_PIVOT_Y 8
#define ba642_PIVOT_W 16
#define ba642_PIVOT_H 16
extern const metasprite_t* const ba642_metasprites[1];

BANKREF_EXTERN(ba642)

extern const palette_color_t ba642_palettes[4];
extern const uint8_t ba642_tiles[64];

#endif
