//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bu322_H
#define METASPRITE_bu322_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bu322_TILE_ORIGIN 0
#define bu322_TILE_W 8
#define bu322_TILE_H 16
#define bu322_WIDTH 16
#define bu322_HEIGHT 16
#define bu322_TILE_COUNT 4
#define bu322_PALETTE_COUNT 1
#define bu322_COLORS_PER_PALETTE 4
#define bu322_TOTAL_COLORS 4
#define bu322_PIVOT_X 8
#define bu322_PIVOT_Y 8
#define bu322_PIVOT_W 16
#define bu322_PIVOT_H 16
extern const metasprite_t* const bu322_metasprites[1];

BANKREF_EXTERN(bu322)

extern const palette_color_t bu322_palettes[4];
extern const uint8_t bu322_tiles[64];

#endif
