//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bu642_H
#define METASPRITE_bu642_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bu642_TILE_ORIGIN 0
#define bu642_TILE_W 8
#define bu642_TILE_H 16
#define bu642_WIDTH 16
#define bu642_HEIGHT 16
#define bu642_TILE_COUNT 4
#define bu642_PALETTE_COUNT 1
#define bu642_COLORS_PER_PALETTE 4
#define bu642_TOTAL_COLORS 4
#define bu642_PIVOT_X 8
#define bu642_PIVOT_Y 8
#define bu642_PIVOT_W 16
#define bu642_PIVOT_H 16
extern const metasprite_t* const bu642_metasprites[1];

BANKREF_EXTERN(bu642)

extern const palette_color_t bu642_palettes[4];
extern const uint8_t bu642_tiles[64];

#endif
