//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_b00_H
#define METASPRITE_b00_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define b00_TILE_ORIGIN 0
#define b00_TILE_W 8
#define b00_TILE_H 16
#define b00_WIDTH 16
#define b00_HEIGHT 16
#define b00_TILE_COUNT 4
#define b00_PALETTE_COUNT 1
#define b00_COLORS_PER_PALETTE 4
#define b00_TOTAL_COLORS 4
#define b00_PIVOT_X 8
#define b00_PIVOT_Y 8
#define b00_PIVOT_W 16
#define b00_PIVOT_H 16
extern const metasprite_t* const b00_metasprites[1];

BANKREF_EXTERN(b00)

extern const palette_color_t b00_palettes[4];
extern const uint8_t b00_tiles[64];

#endif
