//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ba320_H
#define METASPRITE_ba320_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ba320_TILE_ORIGIN 0
#define ba320_TILE_W 8
#define ba320_TILE_H 16
#define ba320_WIDTH 16
#define ba320_HEIGHT 16
#define ba320_TILE_COUNT 4
#define ba320_PALETTE_COUNT 1
#define ba320_COLORS_PER_PALETTE 4
#define ba320_TOTAL_COLORS 4
#define ba320_PIVOT_X 8
#define ba320_PIVOT_Y 8
#define ba320_PIVOT_W 16
#define ba320_PIVOT_H 16
extern const metasprite_t* const ba320_metasprites[1];

BANKREF_EXTERN(ba320)

extern const palette_color_t ba320_palettes[4];
extern const uint8_t ba320_tiles[64];

#endif
