//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ba640_H
#define METASPRITE_ba640_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ba640_TILE_ORIGIN 0
#define ba640_TILE_W 8
#define ba640_TILE_H 16
#define ba640_WIDTH 16
#define ba640_HEIGHT 16
#define ba640_TILE_COUNT 4
#define ba640_PALETTE_COUNT 1
#define ba640_COLORS_PER_PALETTE 4
#define ba640_TOTAL_COLORS 4
#define ba640_PIVOT_X 8
#define ba640_PIVOT_Y 8
#define ba640_PIVOT_W 16
#define ba640_PIVOT_H 16
extern const metasprite_t* const ba640_metasprites[1];

BANKREF_EXTERN(ba640)

extern const palette_color_t ba640_palettes[4];
extern const uint8_t ba640_tiles[64];

#endif
