//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bu320_H
#define METASPRITE_bu320_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bu320_TILE_ORIGIN 0
#define bu320_TILE_W 8
#define bu320_TILE_H 16
#define bu320_WIDTH 16
#define bu320_HEIGHT 16
#define bu320_TILE_COUNT 4
#define bu320_PALETTE_COUNT 1
#define bu320_COLORS_PER_PALETTE 4
#define bu320_TOTAL_COLORS 4
#define bu320_PIVOT_X 8
#define bu320_PIVOT_Y 8
#define bu320_PIVOT_W 16
#define bu320_PIVOT_H 16
extern const metasprite_t* const bu320_metasprites[1];

BANKREF_EXTERN(bu320)

extern const palette_color_t bu320_palettes[4];
extern const uint8_t bu320_tiles[64];

#endif
