//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_b01_H
#define METASPRITE_b01_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define b01_TILE_ORIGIN 0
#define b01_TILE_W 8
#define b01_TILE_H 16
#define b01_WIDTH 16
#define b01_HEIGHT 16
#define b01_TILE_COUNT 4
#define b01_PALETTE_COUNT 1
#define b01_COLORS_PER_PALETTE 4
#define b01_TOTAL_COLORS 4
#define b01_PIVOT_X 8
#define b01_PIVOT_Y 8
#define b01_PIVOT_W 16
#define b01_PIVOT_H 16
extern const metasprite_t* const b01_metasprites[1];

BANKREF_EXTERN(b01)

extern const palette_color_t b01_palettes[4];
extern const uint8_t b01_tiles[64];

#endif
