//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ba321_H
#define METASPRITE_ba321_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ba321_TILE_ORIGIN 0
#define ba321_TILE_W 8
#define ba321_TILE_H 16
#define ba321_WIDTH 16
#define ba321_HEIGHT 16
#define ba321_TILE_COUNT 4
#define ba321_PALETTE_COUNT 1
#define ba321_COLORS_PER_PALETTE 4
#define ba321_TOTAL_COLORS 4
#define ba321_PIVOT_X 8
#define ba321_PIVOT_Y 8
#define ba321_PIVOT_W 16
#define ba321_PIVOT_H 16
extern const metasprite_t* const ba321_metasprites[1];

BANKREF_EXTERN(ba321)

extern const palette_color_t ba321_palettes[4];
extern const uint8_t ba321_tiles[64];

#endif
