//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ba641_H
#define METASPRITE_ba641_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ba641_TILE_ORIGIN 0
#define ba641_TILE_W 8
#define ba641_TILE_H 16
#define ba641_WIDTH 16
#define ba641_HEIGHT 16
#define ba641_TILE_COUNT 4
#define ba641_PALETTE_COUNT 1
#define ba641_COLORS_PER_PALETTE 4
#define ba641_TOTAL_COLORS 4
#define ba641_PIVOT_X 8
#define ba641_PIVOT_Y 8
#define ba641_PIVOT_W 16
#define ba641_PIVOT_H 16
extern const metasprite_t* const ba641_metasprites[1];

BANKREF_EXTERN(ba641)

extern const palette_color_t ba641_palettes[4];
extern const uint8_t ba641_tiles[64];

#endif
