//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bu321_H
#define METASPRITE_bu321_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bu321_TILE_ORIGIN 0
#define bu321_TILE_W 8
#define bu321_TILE_H 16
#define bu321_WIDTH 16
#define bu321_HEIGHT 16
#define bu321_TILE_COUNT 4
#define bu321_PALETTE_COUNT 1
#define bu321_COLORS_PER_PALETTE 4
#define bu321_TOTAL_COLORS 4
#define bu321_PIVOT_X 8
#define bu321_PIVOT_Y 8
#define bu321_PIVOT_W 16
#define bu321_PIVOT_H 16
extern const metasprite_t* const bu321_metasprites[1];

BANKREF_EXTERN(bu321)

extern const palette_color_t bu321_palettes[4];
extern const uint8_t bu321_tiles[64];

#endif
