//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_bu641_H
#define METASPRITE_bu641_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define bu641_TILE_ORIGIN 0
#define bu641_TILE_W 8
#define bu641_TILE_H 16
#define bu641_WIDTH 16
#define bu641_HEIGHT 16
#define bu641_TILE_COUNT 4
#define bu641_PALETTE_COUNT 1
#define bu641_COLORS_PER_PALETTE 4
#define bu641_TOTAL_COLORS 4
#define bu641_PIVOT_X 8
#define bu641_PIVOT_Y 8
#define bu641_PIVOT_W 16
#define bu641_PIVOT_H 16
extern const metasprite_t* const bu641_metasprites[1];

BANKREF_EXTERN(bu641)

extern const palette_color_t bu641_palettes[4];
extern const uint8_t bu641_tiles[64];

#endif
