//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_pipes_H
#define METASPRITE_pipes_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define pipes_TILE_ORIGIN 0
#define pipes_TILE_W 8
#define pipes_TILE_H 8
#define pipes_WIDTH 16
#define pipes_HEIGHT 176
#define pipes_TILE_COUNT 12
#define pipes_PALETTE_COUNT 1
#define pipes_COLORS_PER_PALETTE 4
#define pipes_TOTAL_COLORS 4
#define pipes_MAP_ATTRIBUTES 0
extern const unsigned char pipes_map[];
#define pipes_map_attributes pipes_map

BANKREF_EXTERN(pipes)

extern const palette_color_t pipes_palettes[4];
extern const uint8_t pipes_tiles[192];

#endif
