//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_title_H
#define METASPRITE_title_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define title_TILE_ORIGIN 0
#define title_TILE_W 8
#define title_TILE_H 16
#define title_WIDTH 32
#define title_HEIGHT 64
#define title_TILE_COUNT 22
#define title_PALETTE_COUNT 1
#define title_COLORS_PER_PALETTE 4
#define title_TOTAL_COLORS 4
#define title_PIVOT_X 16
#define title_PIVOT_Y 32
#define title_PIVOT_W 32
#define title_PIVOT_H 64
extern const metasprite_t* const title_metasprites[1];

BANKREF_EXTERN(title)

extern const palette_color_t title_palettes[4];
extern const uint8_t title_tiles[352];

#endif
